### PR TITLE
Invite Activist to become Member_Ceb.md

### PR DESCRIPTION
**Pull request by agentzero1**

### CODE REVIEW

**Comment by agentzero1** [comment]
Why the merging is blocked?

**Comment by agentzero1** [comment]
@caratzky  why is it being blocked ?

**Comment by agentzero1** [comment]
Can you review my contribution?

**Comment by agentzero1** [comment]
Hi I’m still waiting for the approval for this project. I’m hoping for a positive response. Thank you!

**Comment by dckc** [comment]
@agentzero1 writes:
> Why the merging is blocked?

because too many contributors were corrupting the history of important files; see #319. All outstanding pull requests need to be rebased as a result of some clean-up work I did.

I recommend against translation of administrative files such as "Invite Activist to become member".

Also, I recommend against merging any translation pull requests until we establish some quality control (see #302).

**Comment by dckc** [comment]
@lapin7 says the English doc is obsolete: https://github.com/rchain/bounties/issues/162#issuecomment-357885600

I removed it in d0982a5d18

**Pull request closed without merging**
