### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by AyAyRon-P**
Change "several reviewers are involved" to "a minimum of three reviewers are involved"

### CODE REVIEW

**Comment by Ojimadu** [comment]
Would the reviewers be part of the people doing the translation? If yes, I think it's defeating the aim of reviewers. IMO reviewers should be independent of the translation peers.

**Comment by AyAyRon-P** [comment]
@Ojimadu, currently that is the issue. The members translating are also the reviewers or one person is the translator and one person is the reviewer. There is no "checks and balances" to the translation system as it currently stands because there isn't a third(fourth/fifth/sixth) unbiased reviewer. It's simply two people saying "yea, this looks good - issue closed"

**Comment by Ojimadu** [comment]
There needs to be an independent reviewer for selected languages. I would have suggested getting outside help from some translation services but that would increase the overhead of translations and being that translation in itself is not a goal I wouldn't suggest that. Unlike the Chinese community, most translated project has little to no audience otherwise it would have been easier to gage the accuracy of the translations.

**Comment by dckc** [comment]
I'd like to think the translation section doesn't need to be a permanent part of ISSUE_TEMPLATE. I'd like to see it moved to a wiki page, with a just a pointer from ISSUE_TEMPLATE.

**Comment by dckc** [comment]
this is overtaken by moving the translation checklist elsewhere

**Pull request closed without merging**
