### PR TITLE
update contributing_cn

### PR DESCRIPTION
**Pull request by zsluedem**
the contributing_cn file needs to be updated , the message is wrong .

### CODE REVIEW

**Comment by rjl493456442** [comment]
@zsluedem Hey will, since the bounties program has changed a lot and the previous contributing version is already out of date. I have pushed a PR to update the stale files. If you have the time, you can review them!
And i think you can merge this request into #516 .

**Comment by ICA3DaR5** [comment]
So is this the same with #516 ?

**Comment by zsluedem** [comment]
@ICA3DaR5 this one is out of dated . I close it now.

**Comment by zsluedem** [comment]
@ICA3DaR5 #516 is the right one

**Pull request closed without merging**
