### PR TITLE
Spanish translation of 'Invite Activists to become Member.md' file

### PR DESCRIPTION
**Pull request by michaelizer**

### CODE REVIEW

**Comment by David405** [comment]
Nice work @michaelizer

**Comment by David405** [comment]
Nice work @michaelizer

**Comment by David405** [comment]
Nice work @michaelizer

**Comment by dckc** [comment]
@lapin7 says the English doc is obsolete: https://github.com/rchain/bounties/issues/162#issuecomment-357885600

I removed it in d0982a5d18

**Pull request closed without merging**
