### PR TITLE
Turkish Translation for dictionary.md file

### PR DESCRIPTION
**Pull request by mugurcagdas**
Dear Sirs,
I have translated dictionary.md file from EN to my own language (TUR).
I am grateful to you for this project. 
Could you please merge this?
I will continue to translate other part.

Best Regards,

### CODE REVIEW

**Comment by mugurcagdas** [comment]
Hello,
I continue to translate this project files from EN to TR (my own language.) @dckc 
You can see #338  first part.
Could you please check it?
Thanks in advance.

**Comment by ICA3DaR5** [comment]
@mugurcagdas @dckc recommends against translating the dictionary.md file. See also #88 and #105.

**Comment by mugurcagdas** [comment]
Hello,
I have translation competence. You can trust my translates. I just did this translate for my national ppl. If you don't merge them, how could they find it? :(
I didn't delete dictionary.md file, I just create new one for my language as "dictionary_TR.md". You can see similar example PR in #333 
Best Regards,
mugurcagdas

**Comment by dckc** [comment]
@mugurcagdas I should have started by saying:

Welcome! It's great that you're interested to help tell the story of RChain.

But please choose a different document to translate. See the discussion in #302.

**Comment by mugurcagdas** [comment]
Thanks for your fast reply. I will do that :(

**Comment by Ojimadu** [comment]
@mugurcagdas Perhaps you can help translate  the ["How to contribute"](https://github.com/rchain/Members/blob/master/CONTRIBUTING.md)  document to Turkish.

**Comment by mugurcagdas** [comment]
Hello @Ojimadu , thanks for your reply. I already do that before.

**Comment by ICA3DaR5** [comment]
@mugurcagdas Hello, do you have a Discord account? If yes, what's your username?

**Pull request closed without merging**
