### PR TITLE
M> Translating Contributing.md to Indonesia

### PR DESCRIPTION
**Pull request by Pastipas**
Hi @ICA3DaR5 , This is my new pull request for the contributing.md Indonesia translation. I just edited some of the translation from my previous pull request. Hope this one is Ok. Please advice and correction if any.

Thanks

### CODE REVIEW

**Comment by rjl493456442** [comment]
You should keep the original version and move the translation file to the CONTRIBUTING directory. But not sure this translation is necessary.

**Comment by Pastipas** [comment]
Thank for the input @rjl493456442. I am still learning on working with Github, I used to contribute via Crowdin and would like also to try to contribute through Github. should I create my own branch instead of committed directly to Master branch  in order to avoid deleting the original version? And since this translation might not necessary, is there any file that need Indonesia translation in this project? Thanks once again for the input.

**Comment by rjl493456442** [comment]
Not sure, you could ask @lapin7 to make sure the necessity

**Comment by lapin7** [comment]
@rjl493456442 @Pastipas I don't know. I'm not a specialist on Github.
Ask @dckc please

**Pull request closed without merging**
