### PR TITLE
Update Issue template

### PR DESCRIPTION
**Pull request by allancto**
Update issue template to reflect current guidance and norms.

### CODE REVIEW

**Comment by allancto** [comment]
About this PR, its formatted incorrectly. The MD (also edited further) is here. This new template is meant to server several purposes, but the main one is to eliminate manual Translation as being something our Cooperative is interested in investing in (see issue #829 for a proposed automated alternative). The Translation label guides are already signed up in the new Community Development label, and once this PR is accepted we'll be able to remove the Translation label altogether. Thanks! -@allanto

### Proposal and Benefit to RChain

*Please complete by replacing these lines with your proposal.*
*- Describe how the building and implementation of this task will benefit our RChain Cooperative and community. Get in touch with a guide (https://github.com/rchain/bounties/wiki/Bounty-Task-Guides) to align your contribution with goals of our Cooperative and community.* 
*- Please include contact, guides, team, links to background information, repositories where documents or other materials may be viewed while in progress, and any other relevant information.*
*- Will this project require maintenance, and if so what is the plan for ongoing effort?*


### Objectives, Timeline and Budget
*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely. If there are uncertainties please explain (for instance, will try to form a team, or completion date depends upon certain factors).*


_How will we measure completion?_ **[example: pull request merged]**
_Estimated Timeline Required to Complete the Task:_ **[days/weeks]**
_Estimated Budget of Task:_ **$[000]**
_Suggested Budget Valuation Model: [examples: hours and hourly rate, cost of comparable projects, Story Points, special skills required, innovation, novelty]_ 
_Retrospective remarks: [fill in AFTER completion of task and BEFORE final voting. Please provide any additional voting information such as testing, pre release usage or comments, objective and subjective evaluation of accomplishments]_

*See CONTRIBUTING.md for details on budget and reward process.*


### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by dckc** [comment]
Please excuse the delay; I just noticed this PR.

We should talk about [good commit messages](https://informatics.kumc.edu/work/wiki/UsingVersionControl#GoodCommitMessages). A generic "Update Issue template" summary isn't helpful.

I suggest: **Emphasize Community Development over Translation**. But... in the description of the Community Building label I see "Building RChain worldwide communities". If China and Russia are examples of these things, then they're regional communities, not worldwide communities, no?

The "Suggested Budget Valuation Model" change seems unrelated. We should talk about atomic commits too. In any case...

I'm not sure how much room we have to change the Task Identification Form without renegotiating with the board.

In sum: this is by no means only an editorial change. Please open issues for substantive discussion. I suppose we could use #483 .

**Comment by deannald** [comment]
Maybe call it "Regional Community Development"?

But I'm not sure what this PR is trying to accomplish here - piggybacking on #483 would address the change in focus/labeling. I don't know what's going on with the issue template updating business here.

**Comment by allancto** [comment]
@dckc, @deannald, thanks for your comments. @dckc you are absolutely correct, the commit message is awful, I apologize for that. I also agree that this pull request is not atomic, so I will split this into two independent PR's. This PR should address Translation, which will simply remove the Translation section of the template. I will file another PR to address changes intended to provide information we need to help us understand issues as they are submitted and guide voting as they are completed. 

Regarding translation, this has been an issue the bounty system has been trying to address for a long time, certainly including #483 Mar 12. There have been several attempts to address this, yet apparently none of them have been successful. There have been suggestions to limit which documents are candidates, and which languages are candidates. There have been suggestions to automate translation. None of these gained significant traction. Without going into great detail we may observe that at the end of the last voting period (June) >20% of all rewards voted are directly for translation. 

I have made this a priority and worked to gradually achieve consensus in the community that translation may be useful as an organic part of a project but not as a deliverable. @deannald, the purpose of the template is to guide potential contributors. As long as Translation remains part of the template (and Translation remains a label contributors will continue to believe (reasonably) that this work is encouraged. 

Also it's important to recognize that our purpose in this is to support language communities, not geographical regions. Our Chinese community is part of a worldwide Chinese community, our Russian community is a worldwide community, including @golovach.ivan, based in Ukraine. One of our most active Spanish speaking members is @michaelizer, based in Venezuela.  Our purpose is to facilitate  communication and encourage cooperation among our entire RChain Worldwide Community. 

Thanks! -@allanto

**Pull request closed without merging**
