### PR TITLE
 Spanish translation userstory.md

### PR DESCRIPTION
**Pull request by jossue33**
Members/projects/identity/userstory.md
line: 1-52
Number of words:807

### CODE REVIEW

**Comment by BelovedAquila** [comment]
@jossue33 good to know  you are interested in working on Spanish  translation projects,
Please friend, 
- Join https://groups.google.com/forum/#!forum/rchain
- Accept https://github.com/rchain/Members/invitations
- Send your emailaddress + github name to ops@rchain.coop

**Comment by jossue33** [comment]
@BelovedAquila  Okay, you can send me the invitation again because it will not let me enter the link that you put me. 
thanks.

**Comment by BelovedAquila** [comment]
@jossue33 
 - Send your emailaddress + github name to ops@rchain.coop

**Comment by jossue33** [comment]
@BelovedAquila I already sent everything. Thank you

**Comment by dckc** [comment]
@jimscarver is this document important to translate?

**Comment by dckc** [comment]
As a result of some repository clean-up (#319) all PRs need to be rebased.

**Pull request closed without merging**
