### PR TITLE
Translate CONTRIBUTING.md to Indonesia

### PR DESCRIPTION
**Pull request by Pastipas**
I have translate the file to Indonesia and add the name with ID code, stand for Indonesia.

Please advice if there is correction needed, or if you have any comment for the translation.

### CODE REVIEW

**Comment by ICA3DaR5** [comment]
@Pastipas This Pull Requests **deletes** the original ENGLISH CONTRIBUTING.md file and creates the CONTRIBUTING_ID.md file.

**Comment by Pastipas** [comment]
I am so terribly sorry, I didn't aware that was deleting the original file. What should I do to restore the original back? or it was not possible anymore and I have done a very big mistake here.

**Comment by ICA3DaR5** [comment]
@dckc What should @Pastipas do in this case?

**Comment by dckc** [comment]
Start over with a new PR.

@ICA3DaR5 would you like to help him put the document under `_i18n/id`?

**Comment by Pastipas** [comment]
Thank you very much @dckc for the input, will do as you suggested. Feel so relieved that there is no harm has been done but still feel so bad about this. 
@ICA3DaR5 thanks you for your attentive response and look forward for further cooperation within this project. Hope I can be of any help for this project particularly for the need of Indonesia Translation.

**Comment by ICA3DaR5** [comment]
@dckc Sure, so we'll go with that tree format? If so, I'll create a PR that moves all the translations into that tree format.

@Pastipas Just create a PR that doesn't delete the original file, I'll do the rest, is that okay?

**Comment by Pastipas** [comment]
@ICA3DaR5 Yes, I am OK with that. Following @dckc  suggestion for _i18n/id folder, is that mean that all the documents that need to be translate to Indonesia will be in that folder? If it so, it will be very useful, so I know what to contribute next.

**Comment by dckc** [comment]
not all documents; just CONTRIBUTING.md

Other documents in this repository are probably not worth translating. See discussion in #302.

Translations of other documents belong in their respective repository.

**Pull request closed without merging**
