### PR TITLE
Add git workflow section to contrition guide

### PR DESCRIPTION
**Pull request by rjl493456442**

### CODE REVIEW

**Comment by ICA3DaR5** [comment]
This looks nice! Althought I believe the easiest way to do this is is through GitHub only.

1. Fork the repo
2. Create a branch.
3. Make and commit the changes.
4. Create a pull request.

Feedback?

**Comment by rjl493456442** [comment]
@ICA3DaR5 Hey, i describe all the steps in detail so that newbie can follow the instructions to make a correct PR. But if you think it is necessary to make it more simple，you can modify it base on my work. I think all we done is try to explain the workflow clear.

**Comment by ICA3DaR5** [comment]
@rjl493456442 I think most people will not understand running git commands, most people run Windows and setting up a Git environment there is troublesome. Why not focus on how to do all these things from the GitHub interface?

No commands, easier understanding?

**Comment by dckc** [comment]
Before I merge something like this, I intend to fix the history of CONTRIBUTING.md so that blame work work.

**Comment by rjl493456442** [comment]
@dckc You can merge the #353 and #354 together or just accpet the revert PR #356

**Comment by kirkwood** [comment]
For a more in-depth treatment, feel free to link to the [developer git workflow](https://rchain.atlassian.net/wiki/spaces/DOC/pages/44007462/Github+Fork-n-Beans+Workflow) document.

**Comment by rjl493456442** [comment]
@kirkwood Updated. PTAL

**Comment by dckc** [comment]
The link is good.

For the rest, I would like to see it reduced to one heading and one concise paragraph.

**Comment by rjl493456442** [comment]
@dckc Updated, PTAL

**Comment by rjl493456442** [comment]
@dckc yep, you can modify it base on my work if you want.

**Comment by dckc** [comment]
sorry for the delay; I'm juggling too many things.

**Comment by rjl493456442** [comment]
No worry. If the PR doesn't meet your requirement, you can modify directly on my work
发自网易邮箱大师
On 02/22/2018 15:43, Dan Connolly wrote: sorry for the delay; I'm juggling too many things.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rchain/bounties","title":"rchain/bounties","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rchain/bounties"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dckc in #355: sorry for the delay; I'm juggling too many things."}],"action":{"name":"View Pull Request","url":"https://github.com/rchain/bounties/pull/355#issuecomment-367593649"}}}

**Pull request merged**
